name: WP Engine Deployment - Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: PHP Lint
        run: |
          find app/public/wp-content -name "*.php" -type f -print0 | xargs -0 -n1 php -l
      
      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: mbnycd
          REMOTE_PATH: "wp-content/"
          FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
          PHP_LINT: false
          SCRIPT: |
            if [ ! -f ".deployignore" ]; then
              cat > .deployignore <<EOL
            # Version control
            .git
            .gitignore
            .github
            
            # WP Engine specific
            .wpe-*
            .wpengine-conf/
            
            # Cache files
            *.log
            wp-content/cache/
            wp-content/upgrade/
            EOL
            fi 