name: Deploy to WP Engine Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Deploy to WP Engine Production
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_PRIVATE_KEY }}
          WPE_ENV: production
          REMOTE_PATH: "wp-content/"
          PHP_LINT: TRUE
          FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.wpe-push-ignore 