name: WP Engine Deployment - Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: PHP Lint
        run: |
          find app/public/wp-content -name "*.php" -type f -print0 | xargs -0 -n1 php -l
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WPE_SSHG_KEY_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa mbnycd.ssh.wpengine.net >> ~/.ssh/known_hosts
      
      - name: Deploy to WP Engine wp-content
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: mbnycd
          REMOTE_PATH: "wp-content/"
          FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
          PHP_LINT: false
      
      - name: Deploy root files to WP Engine
        run: |
          rsync -azvr --exclude=".*" deploy-root/ mbnycd@mbnycd.ssh.wpengine.net:/sites/mbnycd/public_html/
      
      - name: Create timestamp and execute reset scripts
        run: |
          ssh mbnycd@mbnycd.ssh.wpengine.net '
            # Create a timestamp file in the document root
            echo "$(date +%s)" > /sites/mbnycd/public_html/.deployment-timestamp
            # Ensure the reset scripts exist and are executable
            for script in reset-elementor.php reset-customizer.php reset-styles.php; do
              if [ -f "/sites/mbnycd/public_html/$script" ]; then
                chmod +x "/sites/mbnycd/public_html/$script"
              fi
            done
          ' 