name: WP Engine Deployment - Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: PHP Lint
        run: |
          find app/public/wp-content -name "*.php" -type f -print0 | xargs -0 -n1 php -l
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WPE_SSHG_KEY_PRIVATE }}" > ~/.ssh/wpengine_ed25519
          chmod 600 ~/.ssh/wpengine_ed25519
          ssh-keyscan -t ed25519 mbnyc.ssh.wpengine.net >> ~/.ssh/known_hosts
      
      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: mbnyc
          REMOTE_PATH: "wp-content/"
          FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore 
          PHP_LINT: false
          SCRIPT: |
            if [ ! -f ".deployignore" ]; then
              cat > .deployignore <<EOL
            # Version control
            .git
            .gitignore
            .github
            
            # WP Engine specific
            .wpe-*
            .wpengine-conf/
            
            # Cache files
            *.log
            wp-content/cache/
            wp-content/upgrade/
            EOL
            fi 