name: WP Engine Custom Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: PHP Lint
        run: |
          echo "Running PHP lint checks..."
          find app/public/wp-content -name "*.php" -type f -print0 | xargs -0 -n1 php -l || true
      
      - name: Set up SSH and Deploy
        env:
          SSH_KEY: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        run: |
          # Set up SSH directory and key
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/wpengine_key
          chmod 600 ~/.ssh/wpengine_key
          
          # Add WP Engine to known hosts
          ssh-keyscan -t rsa mbnycd.ssh.wpengine.net >> ~/.ssh/known_hosts
          
          # Verify SSH connection works
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/wpengine_key wpe_gha+mbnycd@mbnycd.ssh.wpengine.net 'echo SSH connection successful'
          
          echo "Deploying to WP Engine..."
          # Deploy using rsync
          rsync -azvr --delete --exclude=".*" --exclude-from=.deployignore \
            -e "ssh -i ~/.ssh/wpengine_key" \
            app/public/wp-content/ \
            wpe_gha+mbnycd@mbnycd.ssh.wpengine.net:sites/mbnycd/wp-content/ 